### ISSUE TITLE
this should be named in lowercase - plugins are not uppercase

### ISSUE THREAD

**Issue by pmgllc** [parallelus/WP-CRAP#1]

**Comment by parallelus** [comment]
The folder name or the repo? Wasn't sure what 'this' is in context to for the change.

**Comment by pmgllc** [comment]
Sorry, the repo. That's the folder name when it downloads.

_Jesse Petersen_
Twitter: @jpetersen

_Petersen Media Group, LLC_
WordPress and Business Services - for the things premium support doesn't
cover.

Product recommendations: hosting: WP Engine http://bit.ly/TqI0Zn ::
domains: NameCheap http://jkp.me/GOvumY :: themes: Genesis Framework
http://bit.ly/TK8mVx :: forms: Gravity Forms http://bit.ly/eKpvFG :: WP
Gallery: Envira Gallery http://shrsl.com/?~71k6 :: opt-ins: OptinMonster
http://jkp.me/1dLAMeH :: WP search: SearchWP http://jkp.me/SearchWP

I'm _100% Genesis Framework http://bit.ly/TK8mVx only_ and one of the few
personally recommended by Genesis staff.

**Comment by parallelus** [comment]
Got it! Makes sense too. It's lowercase on my local so I never noticed.

**Comment by parallelus** [comment]
Fixed.
