### ISSUE TITLE
[question] what to do with theme options?

### ISSUE THREAD

**Issue by senlin** [parallelus/WP-CRAP#3]
Great plugin, that's for sure and I am running it on a few sites already :+1: 

The potential problem however is what to do with theme options?

Before this plugin can become mainstream I think that issue should be tackled. Perhaps make a settings page where the user can set which parts of the Customizer should be removed?

**Comment by senlin** [comment]
The way the [Customizer customizer](https://github.com/cedaro/customizer-customizer) plugin does it, seems a bit more flexible approach :)

**Comment by pmgllc** [comment]
Thanks, and also thanks for the 5-star review on the repository!

We have that under development under a new name. Options for user roles and Customizer areas. I can assure you that Customizer was a huge rabbit hole that took us a couple of hours of solid digging to find the one way to remove it, so the challenge of picking and choosing will be a combination of easier (using one of the early methods we found to remove part of it) and harder (building a framework of options).

**Comment by senlin** [comment]
Great plans Jesse, thanks! Will close this then as it won't be an issue for the next version then.
