### ISSUE TITLE
JS error on admin dashboard

### ISSUE THREAD

**Issue by jaredatch** [parallelus/WP-CRAP#4]
Only problem I seem to run into is with the admin dashboard. Looks like something is trying to load up part of the customizer which isn't obviously there. Just an FYI.

I get this http://cl.ly/image/2r1g301b2d0t

**Comment by parallelus** [comment]
Thanks for reporting this. It look like we needed an adjustment to the priority on: 
`remove_action( 'admin_enqueue_scripts', '_wp_customize_loader_settings', 10);`
